spring.config.import=optional:file:.env[.properties]
spring.application.name=kulliyat

# Öğrenmek için SQL query'leri terminale yazdırıyorum
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Entity'lere göre otomatik olarak schema'yı güncelle
spring.jpa.hibernate.ddl-auto=update