spring.config.import=optional:file:.env[.properties]
spring.application.name=kulliyat

# Entity'lere göre otomatik olarak schema'yı güncelle
spring.jpa.hibernate.ddl-auto=update

app.security.jwt-secret=${JWT_SECRET}
app.bootstrap-admin.username=${BOOTSTRAP_ADMIN_USERNAME:}
app.bootstrap-admin.password=${BOOTSTRAP_ADMIN_PASSWORD:}
app.bootstrap-admin.first-name=${BOOTSTRAP_ADMIN_FIRST_NAME:}
app.bootstrap-admin.last-name=${BOOTSTRAP_ADMIN_LAST_NAME:}
app.bootstrap-admin.role=${BOOTSTRAP_ADMIN_ROLE:ROLE_ADMIN}
